BEGIN TRANSACTION;
INSERT INTO metro_assoc VALUES (1,'Birmingham','http://www.menupix.com/birmingham',1),
 (2,'Huntsville','http://www.menupix.com/huntsville',1),
 (3,'Mobile','http://www.menupix.com/mobile',1),
 (4,'Montgomery','http://www.menupix.com/montgomery',1),
 (5,'Anchorage','http://www.menupix.com/anchorage',2),
 (6,'Fairbanks','http://www.menupix.com/fairbanks',2),
 (7,'Juneau','http://www.menupix.com/juneau',2),
 (8,'Flagstaff','http://www.menupix.com/flagstaff',3),
 (9,'Phoenix','http://www.menupix.com/phoenix',3),
 (10,'Tucson','http://www.menupix.com/tucson',3),
 (11,'Little Rock','http://www.menupix.com/littlerock',4),
 (12,'Bakersfield','http://www.menupix.com/bakersfield',5),
 (13,'Chico','http://www.menupix.com/chico',5),
 (14,'Fresno','http://www.menupix.com/fresno',5),
 (15,'Los Angeles','http://www.menupix.com/losangeles',5),
 (16,'Marin','http://www.menupix.com/marincounty',5),
 (17,'Merced','http://www.menupix.com/merced',5),
 (18,'Modesto','http://www.menupix.com/modesto',5),
 (19,'Napa','http://www.menupix.com/napa',5),
 (20,'Oakland','http://www.menupix.com/oakland',5),
 (21,'Orange County','http://www.menupix.com/orangecounty',5),
 (22,'Palmdale','http://www.menupix.com/palmdale',5),
 (23,'Redding','http://www.menupix.com/redding',5),
 (24,'Riverside County','http://www.menupix.com/riverside',5),
 (25,'Sacramento','http://www.menupix.com/sacramento',5),
 (26,'San Diego','http://www.menupix.com/sandiego',5),
 (27,'San Francisco','http://www.menupix.com/sf',5),
 (28,'San Jose','http://www.menupix.com/sanjose',5),
 (29,'San Luis Obispo','http://www.menupix.com/sanluisobispo',5),
 (30,'San Mateo County','http://www.menupix.com/sanmateo',5),
 (31,'Santa Barbara','http://www.menupix.com/santabarbara',5),
 (32,'Santa Cruz','http://www.menupix.com/santacruz',5),
 (33,'Sonoma','http://www.menupix.com/sonoma',5),
 (34,'Stockton','http://www.menupix.com/stockton',5),
 (35,'Ventura County','http://www.menupix.com/ventura',5),
 (36,'Boulder','http://www.menupix.com/boulder',6),
 (37,'Colorado Springs','http://www.menupix.com/coloradosprings',6),
 (38,'Denver','http://www.menupix.com/denver',6),
 (39,'Fort Collins','http://www.menupix.com/fortcollins',6),
 (40,'Grand Junction','http://www.menupix.com/grandjunction',6),
 (41,'Pueblo','http://www.menupix.com/pueblo',6),
 (42,'Hartford','http://www.menupix.com/hartford',7),
 (43,'New Haven','http://www.menupix.com/newhaven',7),
 (44,'Washington, D.C.','http://www.menupix.com/dc',9),
 (45,'Fort Lauderdale','http://www.menupix.com/fortlauderdale',10),
 (46,'Jacksonville','http://www.menupix.com/jacksonville',10),
 (47,'Miami','http://www.menupix.com/miami',10),
 (48,'Orlando','http://www.menupix.com/orlando',10),
 (49,'Tampa','http://www.menupix.com/tampa',10),
 (50,'Atlanta','http://www.menupix.com/atlanta',11),
 (51,'Augusta','http://www.menupix.com/augusta',11),
 (52,'Columbus','http://www.menupix.com/columbus-ga',11),
 (53,'Macon','http://www.menupix.com/macon',11),
 (54,'Savannah','http://www.menupix.com/savannah',11),
 (55,'Boise','http://www.menupix.com/boise',13),
 (56,'Idaho Falls','http://www.menupix.com/idahofalls',13),
 (57,'Twin Falls','http://www.menupix.com/twinfalls',13),
 (58,'Bloomington','http://www.menupix.com/bloomington',14),
 (59,'Champaign','http://www.menupix.com/champaign',14),
 (60,'Chicago','http://www.menupix.com/chicago',14),
 (61,'Decatur','http://www.menupix.com/decatur',14),
 (62,'Peoria','http://www.menupix.com/peoria',14),
 (63,'Rockford','http://www.menupix.com/rockford',14),
 (64,'Springfield','http://www.menupix.com/springfield-il',14),
 (65,'Bloomington','http://www.menupix.com/bloomington-in',15),
 (66,'Elkhart','http://www.menupix.com/elkhart',15),
 (67,'Evansville','http://www.menupix.com/evansville',15),
 (68,'Fort Wayne','http://www.menupix.com/fortwayne',15),
 (69,'Gary','http://www.menupix.com/gary',15),
 (70,'Indianapolis','http://www.menupix.com/indianapolis',15),
 (71,'Lafayette','http://www.menupix.com/lafayette-in',15),
 (72,'South Bend','http://www.menupix.com/southbend',15),
 (73,'Terre Haute','http://www.menupix.com/terrehaute',15),
 (74,'Valparaiso','http://www.menupix.com/valparaiso',15),
 (75,'Cedar Falls','http://www.menupix.com/cedarfalls',16),
 (76,'Cedar Rapids','http://www.menupix.com/cedarrapids',16),
 (77,'Davenport','http://www.menupix.com/davenport',16),
 (78,'Des Moines','http://www.menupix.com/desmoines',16),
 (79,'Iowa City','http://www.menupix.com/iowacity',16),
 (80,'Sioux City','http://www.menupix.com/siouxcity',16),
 (81,'Kansas City','http://www.menupix.com/kansascity',17),
 (82,'Topeka','http://www.menupix.com/topeka',17),
 (83,'Wichita','http://www.menupix.com/wichita',17),
 (84,'Bowling Green','http://www.menupix.com/bowlinggreen',18),
 (85,'Lexington','http://www.menupix.com/lexington',18),
 (86,'Louisville','http://www.menupix.com/louisville',18),
 (87,'Baton Rouge','http://www.menupix.com/batonrouge',19),
 (88,'Lafayette','http://www.menupix.com/lafayette',19),
 (89,'Lake Charles','http://www.menupix.com/lakecharles',19),
 (90,'Monroe','http://www.menupix.com/monroela',19),
 (91,'New Orleans','http://www.menupix.com/neworleans',19),
 (92,'Shreveport','http://www.menupix.com/shreveport',19),
 (93,'Bangor','http://www.menupix.com/bangor',20),
 (94,'Kennebunkport','http://www.menupix.com/kennebunkport',20),
 (95,'Portland','http://www.menupix.com/portlandme',20),
 (96,'Baltimore','http://www.menupix.com/baltimore',21),
 (97,'Frederick','http://www.menupix.com/frederick-md',21),
 (98,'Amherst','http://www.menupix.com/amherst',22),
 (99,'Boston','http://www.menupix.com/boston',22),
 (100,'Cape Cod','http://www.menupix.com/capecod',22),
 (101,'Lowell','http://www.menupix.com/lowell',22),
 (102,'Worcester','http://www.menupix.com/worcester',22),
 (103,'Ann Arbor','http://www.menupix.com/annarbor',23),
 (104,'Detroit','http://www.menupix.com/detroit',23),
 (105,'Flint','http://www.menupix.com/flint',23),
 (106,'Grand Rapids','http://www.menupix.com/grandrapids',23),
 (107,'Lansing','http://www.menupix.com/lansing',23),
 (108,'Duluth','http://www.menupix.com/duluth-mn',24),
 (109,'Mankato','http://www.menupix.com/mankato-mn',24),
 (110,'Rochester','http://www.menupix.com/rochester-mn',24),
 (111,'Saint Cloud','http://www.menupix.com/saintcloud-mn',24),
 (112,'Twin Cities','http://www.menupix.com/twincities',24),
 (113,'Columbus','http://www.menupix.com/columbus-ms',25),
 (114,'Gulf Coast','http://www.menupix.com/gulfcoast',25),
 (115,'Hattiesburg','http://www.menupix.com/hattiesburg-ms',25),
 (116,'Jackson','http://www.menupix.com/jackson',25),
 (117,'Jones','http://www.menupix.com/jones-ms',25),
 (118,'Meridian','http://www.menupix.com/meridian-ms',25),
 (119,'Tupelo','http://www.menupix.com/tupelo',25),
 (120,'Branson','http://www.menupix.com/branson-mo',26),
 (121,'Cape Girardeau','http://www.menupix.com/capegirardeau',26),
 (122,'Columbia','http://www.menupix.com/columbia-mo',26),
 (123,'Jefferson City','http://www.menupix.com/jeffersoncity',26),
 (124,'Joplin','http://www.menupix.com/joplin-mo',26),
 (125,'Saint Charles','http://www.menupix.com/saintcharles',26),
 (126,'Saint Louis','http://www.menupix.com/saintlouis',26),
 (127,'Springfield','http://www.menupix.com/springfield-mo',26),
 (128,'Billings','http://www.menupix.com/billings',27),
 (129,'Bozeman','http://www.menupix.com/bozeman',27),
 (130,'Great Falls','http://www.menupix.com/greatfalls-mt',27),
 (131,'Helena','http://www.menupix.com/helena-mt',27),
 (132,'Kailspell','http://www.menupix.com/kailspell-mt',27),
 (133,'Missoula','http://www.menupix.com/missoula',27),
 (134,'Kearney','http://www.menupix.com/kearney-ne',28),
 (135,'Lincoln','http://www.menupix.com/lincoln',28),
 (136,'Omaha','http://www.menupix.com/omaha',28),
 (137,'Las Vegas','http://www.menupix.com/lasvegas',29),
 (138,'Reno','http://www.menupix.com/reno',29),
 (139,'Concord','http://www.menupix.com/concord',30),
 (140,'Manchester','http://www.menupix.com/manchester',30),
 (141,'Nashua','http://www.menupix.com/nashua',30),
 (142,'Portsmouth','http://www.menupix.com/portsmouth',30),
 (143,'Salem NH','http://www.menupix.com/salemnh',30),
 (144,'Hoboken','http://www.menupix.com/hoboken',31),
 (145,'Jersey City','http://www.menupix.com/jerseycity',31),
 (146,'Albuquerque','http://www.menupix.com/albuquerque',32),
 (147,'Santa Fe','http://www.menupix.com/santafe',32),
 (148,'Albany','http://www.menupix.com/albany',33),
 (149,'Binghamton','http://www.menupix.com/binghamton',33),
 (150,'Bronx','http://www.menupix.com/bronx',33),
 (151,'Brooklyn','http://www.menupix.com/brooklyn',33),
 (152,'Buffalo','http://www.menupix.com/buffalo',33),
 (153,'Long Island','http://www.menupix.com/longisland',33),
 (154,'Niagara Falls','http://www.menupix.com/niagarafalls',33),
 (155,'New York City','http://www.menupix.com/nyc',33),
 (156,'Queens','http://www.menupix.com/queens',33),
 (157,'Rochester','http://www.menupix.com/rochester',33),
 (158,'Staten Island','http://www.menupix.com/statenisland',33),
 (159,'Syracuse','http://www.menupix.com/syracuse',33),
 (160,'Utica','http://www.menupix.com/utica',33),
 (161,'Westchester','http://www.menupix.com/westchester',33),
 (162,'Asheville','http://www.menupix.com/asheville',34),
 (163,'Chapel Hill','http://www.menupix.com/chapelhill',34),
 (164,'Charlotte','http://www.menupix.com/charlotte',34),
 (165,'Durham','http://www.menupix.com/durham',34),
 (166,'Fayetteville','http://www.menupix.com/fayetteville',34),
 (167,'Gastonia','http://www.menupix.com/gastonia',34),
 (168,'Greensboro','http://www.menupix.com/greensboro',34),
 (169,'Raleigh','http://www.menupix.com/raleigh',34),
 (170,'Wilmington NC','http://www.menupix.com/wilmington',34),
 (171,'Winston-Salem','http://www.menupix.com/winston-salem',34),
 (172,'Bismarck','http://www.menupix.com/bismarck',35),
 (173,'Fargo','http://www.menupix.com/fargo',35),
 (174,'Grand Forks','http://www.menupix.com/grandforks',35),
 (175,'Akron','http://www.menupix.com/akron',36),
 (176,'Canton','http://www.menupix.com/canton',36),
 (177,'Cincinnati','http://www.menupix.com/cincinnati',36),
 (178,'Cleveland','http://www.menupix.com/cleveland',36),
 (179,'Columbus','http://www.menupix.com/columbus',36),
 (180,'Dayton','http://www.menupix.com/dayton',36),
 (181,'Toledo','http://www.menupix.com/toledo',36),
 (182,'Youngstown','http://www.menupix.com/youngstown',36),
 (183,'Enid','http://www.menupix.com/enid-ok',37),
 (184,'Lawton','http://www.menupix.com/lawton-ok',37),
 (185,'Muskogee','http://www.menupix.com/muskogee-ok',37),
 (186,'Oklahoma City','http://www.menupix.com/oklahomacity',37),
 (187,'Ponca City','http://www.menupix.com/poncacity-ok',37),
 (188,'Stillwater','http://www.menupix.com/stillwater',37),
 (189,'Tulsa','http://www.menupix.com/tulsa',37),
 (190,'Bend','http://www.menupix.com/bend',38),
 (191,'Eugene','http://www.menupix.com/eugene',38),
 (192,'Medford','http://www.menupix.com/medford',38),
 (193,'Portland','http://www.menupix.com/portland',38),
 (194,'Salem','http://www.menupix.com/salem',38),
 (195,'Allentown','http://www.menupix.com/allentown',39),
 (196,'Erie','http://www.menupix.com/erie',39),
 (197,'Harrisburg','http://www.menupix.com/harrisburg',39),
 (198,'Philadelphia','http://www.menupix.com/philadelphia',39),
 (199,'Pittsburgh','http://www.menupix.com/pittsburgh',39),
 (200,'Scranton','http://www.menupix.com/scranton',39),
 (201,'Providence','http://www.menupix.com/providence',40),
 (202,'Charleston','http://www.menupix.com/charleston',41),
 (203,'Columbia','http://www.menupix.com/columbia',41),
 (204,'Greenville','http://www.menupix.com/greenville',41),
 (205,'Hilton Head','http://www.menupix.com/hiltonhead',41),
 (206,'Myrtle Beach','http://www.menupix.com/myrtlebeach',41),
 (207,'Spartanburg','http://www.menupix.com/spartanburg',41),
 (208,'Rapid City','http://www.menupix.com/rapidcity',42),
 (209,'Sioux Falls','http://www.menupix.com/siouxfalls',42),
 (210,'Chattanooga','http://www.menupix.com/chattanooga',43),
 (211,'Jackson','http://www.menupix.com/jackson-tn',43),
 (212,'Johnson City','http://www.menupix.com/johnsoncity-tn',43),
 (213,'Knoxville','http://www.menupix.com/knoxville',43),
 (214,'Memphis','http://www.menupix.com/memphis',43),
 (215,'Nashville','http://www.menupix.com/nashville',43),
 (216,'Abilene','http://www.menupix.com/abilene',44),
 (217,'Amarillo','http://www.menupix.com/amarillo',44),
 (218,'Austin','http://www.menupix.com/austin',44),
 (219,'Beaumont','http://www.menupix.com/beaumont',44),
 (220,'Brownsville','http://www.menupix.com/brownsville',44),
 (221,'College Station','http://www.menupix.com/collegestation',44),
 (222,'Corpus Christi','http://www.menupix.com/corpuschristi',44),
 (223,'Dallas','http://www.menupix.com/dallas',44),
 (224,'El Paso','http://www.menupix.com/elpaso',44),
 (225,'Galveston','http://www.menupix.com/galveston',44),
 (226,'Houston','http://www.menupix.com/houston',44),
 (227,'Laredo','http://www.menupix.com/laredo',44),
 (228,'Lubbock','http://www.menupix.com/lubbock',44),
 (229,'Mcallen','http://www.menupix.com/mcallen',44),
 (230,'Midland','http://www.menupix.com/midland',44),
 (231,'Odessa','http://www.menupix.com/odessa',44),
 (232,'San Antonio','http://www.menupix.com/sanantonio',44),
 (233,'Tyler','http://www.menupix.com/tyler',44),
 (234,'Waco','http://www.menupix.com/waco',44),
 (235,'Ogden','http://www.menupix.com/ogden',45),
 (236,'Provo','http://www.menupix.com/provo',45),
 (237,'Saint George','http://www.menupix.com/saintgeorge',45),
 (238,'Salt Lake City','http://www.menupix.com/saltlakecity',45),
 (239,'Burlington','http://www.menupix.com/burlington',46),
 (240,'Charlottesville','http://www.menupix.com/charlottesville',47),
 (241,'Fredericksburg','http://www.menupix.com/fredericksburg',47),
 (242,'Lynchburg','http://www.menupix.com/lynchburg',47),
 (243,'Manassas','http://www.menupix.com/manassas',47),
 (244,'Richmond','http://www.menupix.com/richmond',47),
 (245,'Roanoke','http://www.menupix.com/roanoke',47),
 (246,'Virginia Beach','http://www.menupix.com/virginiabeach',47),
 (247,'Williamsburg','http://www.menupix.com/williamsburg',47),
 (248,'Seattle','http://www.menupix.com/seattle',48),
 (249,'Spokane','http://www.menupix.com/spokane',48),
 (250,'Yakima','http://www.menupix.com/yakima',48),
 (251,'Beckley','http://www.menupix.com/beckley-wv',49),
 (252,'Charleston','http://www.menupix.com/charleston-wv',49),
 (253,'Huntington','http://www.menupix.com/huntington-wv',49),
 (254,'Morgantown','http://www.menupix.com/morgantown-wv',49),
 (255,'Parkersburg','http://www.menupix.com/parkersburg-wv',49),
 (256,'Appleton','http://www.menupix.com/appleton',50),
 (257,'Eau Claire','http://www.menupix.com/eauclaire',50),
 (258,'Green Bay','http://www.menupix.com/greenbay',50),
 (259,'Kenosha','http://www.menupix.com/kenosha',50),
 (260,'La Crosse','http://www.menupix.com/lacrosse',50),
 (261,'Madison','http://www.menupix.com/madison',50),
 (262,'Milwaukee','http://www.menupix.com/milwaukee',50),
 (263,'Oshkosh','http://www.menupix.com/oshkosh',50),
 (264,'Racine','http://www.menupix.com/racine',50),
 (265,'Sheboygan','http://www.menupix.com/sheboygan',50),
 (266,'Waukesha','http://www.menupix.com/waukesha',50),
 (267,'Calgary','http://www.menupix.com/calgary/',52),
 (268,'Edmonton','http://www.menupix.com/edmonton/',52),
 (269,'Montreal','http://www.menupix.com/montreal/',60),
 (270,'Ottawa','http://www.menupix.com/ottawa/',58),
 (271,'Regina','http://www.menupix.com/regina/',61),
 (272,'Saskatoon','http://www.menupix.com/saskatoon/',61),
 (273,'Toronto','http://www.menupix.com/toronto/',58),
 (274,'Vancouver','http://www.menupix.com/vancouver/',53),
 (275,'Winnipeg','http://www.menupix.com/winnipeg/',54),
 (276,'Victoria','http://www.menupix.com/victoria/',53);
COMMIT;
