BEGIN TRANSACTION;
INSERT INTO state (id,name,abbr,state_link) VALUES (1,'Alabama','AL','http://www.menupix.com/alabama'),
 (2,'Alaska','AK','http://www.menupix.com/alaska'),
 (3,'Arizona','AZ','http://www.menupix.com/arizona'),
 (4,'Arkansas','AR','http://www.menupix.com/arkansas'),
 (5,'California','CA','http://www.menupix.com/california'),
 (6,'Colorado','CO','http://www.menupix.com/colorado'),
 (7,'Connecticut','CT','http://www.menupix.com/connecticut'),
 (8,'Delaware','DE','http://www.menupix.com/delaware'),
 (9,'Washington, D.C.','DC','http://www.menupix.com/dc'),
 (10,'Florida','FL','http://www.menupix.com/florida'),
 (11,'Georgia','GA','http://www.menupix.com/georgia'),
 (12,'Hawaii','HI','http://www.menupix.com/hawaii'),
 (13,'Idaho','ID','http://www.menupix.com/idaho'),
 (14,'Illinois','IL','http://www.menupix.com/illinois'),
 (15,'Indiana','IN','http://www.menupix.com/indiana'),
 (16,'Iowa','IA','http://www.menupix.com/iowa'),
 (17,'Kansas','KS','http://www.menupix.com/kansas'),
 (18,'Kentucky','KY','http://www.menupix.com/kentucky'),
 (19,'Louisiana','LA','http://www.menupix.com/louisiana'),
 (20,'Maine','ME','http://www.menupix.com/maine'),
 (21,'Maryland','MD','http://www.menupix.com/maryland'),
 (22,'Massachusetts','MA','http://www.menupix.com/massachusetts'),
 (23,'Michigan','MI','http://www.menupix.com/michigan'),
 (24,'Minnesota','MN','http://www.menupix.com/minnesota'),
 (25,'Mississippi','MS','http://www.menupix.com/mississippi'),
 (26,'Missouri','MO','http://www.menupix.com/missouri'),
 (27,'Montana','MT','http://www.menupix.com/montana'),
 (28,'Nebraska','NE','http://www.menupix.com/nebraska'),
 (29,'Nevada','NV','http://www.menupix.com/nevada'),
 (30,'New Hampshire','NH','http://www.menupix.com/newhampshire'),
 (31,'New Jersey','NJ','http://www.menupix.com/newjersey'),
 (32,'New Mexico','NM','http://www.menupix.com/newmexico'),
 (33,'New York','NY','http://www.menupix.com/newyork'),
 (34,'North Carolina','NC','http://www.menupix.com/northcarolina'),
 (35,'North Dakota','ND','http://www.menupix.com/northdakota'),
 (36,'Ohio','OH','http://www.menupix.com/ohio'),
 (37,'Oklahoma','OK','http://www.menupix.com/oklahoma'),
 (38,'Oregon','OR','http://www.menupix.com/oregon'),
 (39,'Pennsylvania','PA','http://www.menupix.com/pennsylvania'),
 (40,'Rhode Island','RI','http://www.menupix.com/rhodeisland'),
 (41,'South Carolina','SC','http://www.menupix.com/southcarolina'),
 (42,'South Dakota','SD','http://www.menupix.com/southdakota'),
 (43,'Tennessee','TN','http://www.menupix.com/tennessee'),
 (44,'Texas','TX','http://www.menupix.com/texas'),
 (45,'Utah','UT','http://www.menupix.com/utah'),
 (46,'Vermont','VT','http://www.menupix.com/vermont'),
 (47,'Virginia','VA','http://www.menupix.com/virginia'),
 (48,'Washington','WA','http://www.menupix.com/washington'),
 (49,'West Virginia','WV','http://www.menupix.com/westvirginia'),
 (50,'Wisconsin','WI','http://www.menupix.com/wisconsin'),
 (51,'Wyoming','WY','http://www.menupix.com/wyoming'),
 (52,'Alberta','AB','http://www.menupix.com/alberta/'),
 (53,'British Columbia','ON','http://www.menupix.com/british-columbia/'),
 (54,'Manitoba','MB','http://www.menupix.com/manitoba/'),
 (55,'New Brunswick','NB','http://www.menupix.com/new-brunswick/'),
 (56,'Newfoundland','NL','http://www.menupix.com/newfoundland/'),
 (57,'Nova Scotia','NS','http://www.menupix.com/nova-scotia/'),
 (58,'Ontario','ON','http://www.menupix.com/ontario/'),
 (59,'Prince Edward Island','PE','http://www.menupix.com/prince-edward-island/'),
 (60,'Quebec','QC','http://www.menupix.com/quebec/'),
 (61,'Saskatchewan','SK','http://www.menupix.com/saskatchewan/'),
 (62,'Yukon','YT','http://www.menupix.com/yukon/'),
 (63,'Northwest Territories','NT',NULL),
 (64,'Nunavut','NU',NULL);
CREATE INDEX ix_restaurant_links_state_id ON restaurant_links (state_id);
CREATE INDEX ix_restaurant_links_county_id ON restaurant_links (county_id);
CREATE INDEX ix_restaurant_links_city_metro_id ON restaurant_links (city_metro_id);
CREATE INDEX ix_metro_assoc_state_id ON metro_assoc (state_id);
CREATE INDEX ix_county_state_id ON county (state_id);
CREATE INDEX ix_city_metro_state_id ON city_metro (state_id);
CREATE INDEX ix_city_metro_county_id ON city_metro (county_id);
COMMIT;
